### ISSUE TITLE
Incorrect Role binding

### ISSUE THREAD

**Issue by ganniterix** [isovalent/cilium-olm#16]
By following the procedure in the documentation:

https://docs.cilium.io/en/v1.13/installation/k8s-install-openshift-okd/#k8s-install-openshift-okd

The following file (from the manifests folder) is referencing the wrong role

```cluster-network-06-cilium-00006-leader-election-rolebinding.yaml```

```
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: leader-election
  namespace: cilium
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: leader-election
subjects:
  - kind: ServiceAccount
    name: cilium-olm
    namespace: cilium
```

The roleRef should change to:

```
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: cilium-olm-leader-election
```
